version: 2.1

workflows:
  test-DAC-Portal:
    jobs:
      - run-tests:
          name: DAC-Portal
jobs:
  run-tests:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Start MONGO
          command: |
            docker-compose -f docker-compose.tests.yml up -d mongo
            docker-compose -f docker-compose.tests.yml logs
      - run:
          name: Wait for mongodb
          command: |
            docker-compose -f docker-compose.tests.yml logs mongo
            dockerize -wait tcp://172.21.0.1:27017 -timeout 5m
      - run:
          name: KC providers permissions
          command: |
            sudo chmod -R 777 ./
            docker-compose -f docker-compose.tests.yml logs
            sleep 5
      - run:
          name: Start KEYCLOAK
          command: |
            docker-compose -f docker-compose.tests.yml up -d keycloak
            docker-compose -f docker-compose.tests.yml logs
      - run:
          name: Run DAC-Portal
          command: |
            docker-compose -f docker-compose.tests.yml up -d dac-portal
            docker-compose -f docker-compose.tests.yml logs
            sleep 60
      - run:
          name: Start Permissions-API
          command: |
            docker-compose -f docker-compose.tests.yml up -d permissions-api
            docker-compose -f docker-compose.tests.yml logs
            sleep 60
      - run:
          name: Run tests with Cypress
          command: | 
            docker-compose -f docker-compose.tests.yml logs
            sleep 60
            docker-compose -f docker-compose.tests.yml exec dac-portal npm run cypress:run
